import { useCallback, useEffect, useState } from "react";
import { Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { useRouter } from "expo-router";
import Ionicons from "@expo/vector-icons/Ionicons";
import { GlassCard } from "@/components/GlassCard";
import { api, ApiError } from "@/lib/api";

type Address = { id: string; label: string; line1: string; line2?: string | null; city: string; state: string; country?: string | null; isDefault?: boolean };

export default function AddressesScreen() {
  const router = useRouter();
  const [addresses, setAddresses] = useState<Address[]>([]);
  const [loading, setLoading] = useState(true);
  const [showForm, setShowForm] = useState(false);
  const [saving, setSaving] = useState(false);
  const [form, setForm] = useState({ label: "Home", line1: "", line2: "", city: "", state: "", country: "Nigeria", isDefault: false });
  const load = useCallback(async () => { try { const r = await api<{ addresses: Address[] }>("/api/addresses"); setAddresses(r.addresses); } catch (e) { Alert.alert("Could not load addresses", e instanceof ApiError ? e.message : "Please try again."); } finally { setLoading(false); } }, []);
  useEffect(() => { load(); }, [load]);
  async function add() { if (!form.line1.trim() || !form.city.trim() || !form.state.trim()) return Alert.alert("Missing details", "Enter your address, city and state."); setSaving(true); try { await api("/api/addresses", { method: "POST", body: JSON.stringify({ ...form, line1: form.line1.trim(), line2: form.line2.trim() || undefined, city: form.city.trim(), state: form.state.trim() }) }); setForm({ label: "Home", line1: "", line2: "", city: "", state: "", country: "Nigeria", isDefault: false }); setShowForm(false); await load(); } catch (e) { Alert.alert("Could not save", e instanceof ApiError ? e.message : "Please try again."); } finally { setSaving(false); } }
  function remove(id: string) { Alert.alert("Remove address", "Delete this saved address?", [{ text: "Cancel", style: "cancel" }, { text: "Remove", style: "destructive", onPress: async () => { try { await api(`/api/addresses/${id}`, { method: "DELETE" }); setAddresses((items) => items.filter((item) => item.id !== id)); } catch (e) { Alert.alert("Could not remove", e instanceof ApiError ? e.message : "Please try again."); } } }]); }
  return <ScrollView style={styles.screen} contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><View style={styles.header}><Pressable onPress={() => router.back()} style={styles.iconButton}><Ionicons name="arrow-back" size={21} color="#111" /></Pressable><Text style={styles.title}>Saved addresses</Text><Pressable onPress={() => setShowForm((v) => !v)} style={styles.iconButton}><Ionicons name={showForm ? "close" : "add"} size={22} color="#111" /></Pressable></View>
    {showForm && <GlassCard style={styles.form} intensity={26}><Field label="Label" value={form.label} onChangeText={(v) => setForm({ ...form, label: v })} /><Field label="Address" value={form.line1} onChangeText={(v) => setForm({ ...form, line1: v })} /><Field label="Address line 2" value={form.line2} onChangeText={(v) => setForm({ ...form, line2: v })} /><View style={styles.two}><View style={styles.half}><Field label="City" value={form.city} onChangeText={(v) => setForm({ ...form, city: v })} /></View><View style={styles.half}><Field label="State" value={form.state} onChangeText={(v) => setForm({ ...form, state: v })} last /></View></View><Pressable onPress={() => setForm({ ...form, isDefault: !form.isDefault })} style={styles.defaultRow}><Ionicons name={form.isDefault ? "checkbox" : "square-outline"} size={20} color="#111" /><Text style={styles.defaultText}>Make this my default address</Text></Pressable><Pressable disabled={saving} onPress={add} style={[styles.button, saving && styles.disabled]}><Text style={styles.buttonText}>{saving ? "Saving…" : "Save address"}</Text></Pressable></GlassCard>}
    {!loading && addresses.length === 0 && !showForm && <GlassCard style={styles.empty} intensity={20}><Ionicons name="location-outline" size={27} color="#777" /><Text style={styles.emptyTitle}>No saved addresses</Text><Text style={styles.emptyText}>Add an address to make checkout faster.</Text></GlassCard>}
    {addresses.map((a) => <GlassCard key={a.id} style={styles.address} intensity={22}><View style={styles.addressTop}><View style={styles.addressIcon}><Ionicons name="location-outline" size={19} color="#111" /></View><View style={styles.copy}><View style={styles.labelRow}><Text style={styles.addressLabel}>{a.label}</Text>{a.isDefault && <Text style={styles.badge}>DEFAULT</Text>}</View><Text style={styles.line}>{a.line1}{a.line2 ? `, ${a.line2}` : ""}</Text><Text style={styles.muted}>{a.city}, {a.state}, {a.country ?? "Nigeria"}</Text></View><Pressable onPress={() => remove(a.id)}><Ionicons name="trash-outline" size={19} color="#b42318" /></Pressable></View></GlassCard>)}
  </ScrollView>;
}
function Field({ label, last, ...props }: { label: string; last?: boolean } & React.ComponentProps<typeof TextInput>) { return <View style={[styles.field, !last && styles.border]}><Text style={styles.fieldLabel}>{label}</Text><TextInput {...props} style={styles.input} placeholderTextColor="#aaa" /></View>; }
const styles = StyleSheet.create({ screen:{flex:1,backgroundColor:"#f7f7f7"},content:{padding:18,paddingTop:58,paddingBottom:60},header:{flexDirection:"row",alignItems:"center",marginBottom:20},iconButton:{width:42,height:42,borderRadius:14,backgroundColor:"rgba(255,255,255,.72)",alignItems:"center",justifyContent:"center"},title:{flex:1,textAlign:"center",fontSize:20,fontWeight:"800",color:"#111"},form:{paddingHorizontal:16,paddingBottom:16,borderRadius:20,marginBottom:16},field:{paddingVertical:11},border:{borderBottomWidth:1,borderBottomColor:"rgba(0,0,0,.06)"},fieldLabel:{fontSize:10,color:"#999",marginBottom:3},input:{fontSize:14,color:"#111",fontWeight:"600",paddingVertical:3},two:{flexDirection:"row",gap:12},half:{flex:1},defaultRow:{flexDirection:"row",alignItems:"center",gap:9,paddingVertical:12},defaultText:{fontSize:13,color:"#444",fontWeight:"600"},button:{height:50,borderRadius:15,backgroundColor:"#111",alignItems:"center",justifyContent:"center",marginTop:8},buttonText:{color:"#fff",fontWeight:"800"},disabled:{opacity:.55},empty:{padding:24,alignItems:"center",borderRadius:20},emptyTitle:{fontSize:16,fontWeight:"800",color:"#111",marginTop:9},emptyText:{fontSize:13,color:"#888",marginTop:4,textAlign:"center"},address:{padding:16,borderRadius:20,marginBottom:12},addressTop:{flexDirection:"row",alignItems:"flex-start"},addressIcon:{width:40,height:40,borderRadius:13,backgroundColor:"rgba(0,0,0,.05)",alignItems:"center",justifyContent:"center"},copy:{flex:1,marginLeft:11,marginRight:8},labelRow:{flexDirection:"row",alignItems:"center",gap:7},addressLabel:{fontSize:15,fontWeight:"800",color:"#111"},badge:{fontSize:8,fontWeight:"800",color:"#555",letterSpacing:.7},line:{fontSize:13,color:"#444",marginTop:6},muted:{fontSize:12,color:"#888",marginTop:3}}
