import { Stack, useLocalSearchParams } from "expo-router";
import { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, RefreshControl, ScrollView, StyleSheet, Text, View } from "react-native";
import { api, ApiError } from "@/lib/api";

type TrackingResult = { orderNumber?: string; createdAt?: string; vendorOrders?: Array<{ id?: string; vendor?: { name?: string }; status?: string; estimatedDeliveryDate?: string; trackingNumber?: string; events?: Array<{ status?: string; description?: string; createdAt?: string }> }> };
const checkpoints = ["Order confirmed", "Order is being packaged", "Order is being shipped", "Order just arrived Destination country", "Order is out for delivery"];
export default function TrackOrderScreen() {
  const { orderNumber } = useLocalSearchParams<{ orderNumber: string }>();
  const [result, setResult] = useState<TrackingResult | null>(null); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false); const [error, setError] = useState("");
  const load = useCallback(async (refresh = false) => { if (!orderNumber) return; refresh ? setRefreshing(true) : setLoading(true); setError(""); try { setResult(await api<TrackingResult>(`/api/tracking/order/${encodeURIComponent(orderNumber)}`, { auth: true })); } catch (err) { setError(err instanceof ApiError ? err.message : "Could not load tracking."); } finally { setLoading(false); setRefreshing(false); } }, [orderNumber]);
  useEffect(() => { load(); const timer = setInterval(() => load(true), 30000); return () => clearInterval(timer); }, [load]);
  return <View style={styles.screen}><Stack.Screen options={{ headerShown: true, title: "Track order" }} />{loading ? <View style={styles.center}><ActivityIndicator size="large" /></View> : error ? <View style={styles.center}><Text style={styles.error}>{error}</Text></View> : <ScrollView refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => load(true)} />} contentContainerStyle={styles.content}><Text style={styles.label}>TRACKING</Text><Text style={styles.title}>{result?.orderNumber ?? orderNumber}</Text>{(result?.vendorOrders ?? []).map((vendorOrder, index) => <View key={vendorOrder.id ?? index} style={styles.vendor}><Text style={styles.vendorName}>{vendorOrder.vendor?.name ?? "TTFL vendor"}</Text><Text style={styles.status}>{vendorOrder.status ?? "Processing"}</Text><View style={styles.timeline}>{checkpoints.map((checkpoint, i) => { const event = vendorOrder.events?.[i]; const active = Boolean(event) || (vendorOrder.status === "DELIVERED" && i === checkpoints.length - 1); return <View key={checkpoint} style={styles.step}><View style={[styles.dot, active && styles.dotActive]}><Text style={styles.dotText}>{i + 1}</Text></View><View style={styles.stepBody}><Text style={[styles.stepTitle, active && styles.stepActive]}>{checkpoint}</Text>{event?.description && <Text style={styles.event}>{event.description}</Text>}{event?.createdAt && <Text style={styles.time}>{new Date(event.createdAt).toLocaleString()}</Text>}</View></View>; })}</View></View>)}</ScrollView>}</View>;
}
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: "#fff" }, content: { padding: 20, paddingBottom: 40 }, center: { flex: 1, alignItems: "center", justifyContent: "center" }, label: { color: "#9ca3af", fontSize: 11, fontWeight: "800", letterSpacing: 1.2 }, title: { fontSize: 28, fontWeight: "800", marginTop: 5, color: "#111" }, vendor: { borderWidth: 1, borderColor: "#ededed", borderRadius: 18, padding: 18, marginTop: 22 }, vendorName: { fontSize: 18, fontWeight: "800", color: "#111" }, status: { color: "#6b7280", marginTop: 4 }, timeline: { marginTop: 22 }, step: { flexDirection: "row", minHeight: 72 }, dot: { width: 30, height: 30, borderRadius: 15, backgroundColor: "#e5e7eb", alignItems: "center", justifyContent: "center" }, dotActive: { backgroundColor: "#111" }, dotText: { color: "#fff", fontSize: 11, fontWeight: "800" }, stepBody: { flex: 1, marginLeft: 12, paddingBottom: 14 }, stepTitle: { fontWeight: "600", color: "#9ca3af" }, stepActive: { color: "#111", fontWeight: "800" }, event: { color: "#6b7280", marginTop: 4, lineHeight: 19 }, time: { color: "#9ca3af", fontSize: 11, marginTop: 4 }, error: { color: "#dc2626" }
});
