import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { useAuth } from "@/lib/auth";

export default function AccountScreen() {
  const { user, signOut } = useAuth();
  async function logout() { Alert.alert("Sign out", "Are you sure you want to sign out?", [{ text: "Cancel", style: "cancel" }, { text: "Sign out", style: "destructive", onPress: () => signOut() }]); }
  return <ScrollView style={styles.screen} contentContainerStyle={styles.content}><Text style={styles.title}>Account</Text><View style={styles.profile}><View style={styles.avatar}><Text style={styles.avatarText}>{user?.firstName?.[0]?.toUpperCase() ?? "T"}</Text></View><View style={styles.profileText}><Text style={styles.name}>{user?.firstName} {user?.lastName}</Text><Text style={styles.email}>{user?.email}</Text></View></View><View style={styles.card}><Row label="Phone" value={user?.phone ?? "Not added"} /><Row label="Email status" value={user?.emailVerified ? "Verified" : "Not verified"} /><Row label="Account" value={user?.role ?? "CUSTOMER"} /></View><Pressable style={styles.logout} onPress={logout}><Text style={styles.logoutText}>Sign out</Text></Pressable></ScrollView>;
}
function Row({ label, value }: { label: string; value: string }) { return <View style={styles.row}><Text style={styles.label}>{label}</Text><Text style={styles.value}>{value}</Text></View>; }
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: "#fff" }, content: { padding: 20, paddingTop: 60 }, title: { fontSize: 30, fontWeight: "800", color: "#111", marginBottom: 24 }, profile: { flexDirection: "row", alignItems: "center", marginBottom: 24 }, avatar: { width: 64, height: 64, borderRadius: 32, backgroundColor: "#111", alignItems: "center", justifyContent: "center" }, avatarText: { color: "#fff", fontSize: 24, fontWeight: "800" }, profileText: { marginLeft: 14 }, name: { fontSize: 19, fontWeight: "800", color: "#111" }, email: { color: "#6b7280", marginTop: 4 }, card: { borderWidth: 1, borderColor: "#ededed", borderRadius: 18, padding: 4 }, row: { minHeight: 58, paddingHorizontal: 14, borderBottomWidth: 1, borderBottomColor: "#f0f0f0", justifyContent: "center" }, label: { color: "#9ca3af", fontSize: 12 }, value: { color: "#111", fontWeight: "600", marginTop: 3 }, logout: { height: 52, borderRadius: 14, backgroundColor: "#f3f4f6", alignItems: "center", justifyContent: "center", marginTop: 20 }, logoutText: { color: "#b91c1c", fontWeight: "800" }
});
