import { Ionicons } from "@expo/vector-icons";
import { useCallback,useEffect,useState } from "react";
import { ActivityIndicator,Pressable,RefreshControl,ScrollView,StyleSheet,Text,View } from "react-native";
import { router } from "expo-router";
import { GlassCard } from "@/components/GlassCard";
import { api,ApiError } from "@/lib/api";
import { theme,money } from "@/lib/theme";
type Order={id?:string;orderNumber:string;status?:string;createdAt?:string;total?:number;currency?:string};type ResponseShape=Order[]|{orders?:Order[];items?:Order[]};
export default function OrdersScreen(){const[orders,setOrders]=useState<Order[]>([]);const[loading,setLoading]=useState(true);const[refreshing,setRefreshing]=useState(false);const[error,setError]=useState("");
const load=useCallback(async(refresh=false)=>{if(refresh)setRefreshing(true);else setLoading(true);setError("");try{const result=await api<ResponseShape>("/api/orders/me",{auth:true});setOrders(Array.isArray(result)?result:result.orders??result.items??[])}catch(err){setError(err instanceof ApiError?err.message:"Could not load your orders.")}finally{setLoading(false);setRefreshing(false)}},[]);
useEffect(()=>{load()},[load]);
if(loading)return <View style={styles.center}><ActivityIndicator color={theme.colors.ember600}/></View>;
return <ScrollView style={styles.screen} contentContainerStyle={styles.content} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>load(true)}/>}><Text style={styles.eyebrow}>TTFL STORE</Text><Text style={styles.title}>Your orders</Text><Text style={styles.subtitle}>Keep an eye on everything you have bought.</Text>{!!error&&<GlassCard style={styles.message}><Text style={styles.error}>{error}</Text><Pressable onPress={()=>load()} style={styles.retry}><Text style={styles.retryText}>Try again</Text></Pressable></GlassCard>}{!error&&orders.length===0&&<GlassCard style={styles.empty}><View style={styles.emptyIcon}><Ionicons name="cube-outline" size={21} color={theme.colors.graphite600}/></View><Text style={styles.emptyTitle}>No orders yet</Text><Text style={styles.emptyCopy}>Your TTFL purchases will appear here once you place an order.</Text></GlassCard>}{orders.map(order=><Pressable key={order.id??order.orderNumber} onPress={()=>router.push({pathname:"/orders/[orderNumber]",params:{orderNumber:order.orderNumber}})} style={({pressed})=>[styles.press,pressed&&styles.pressed]}><GlassCard style={styles.card}><View style={styles.row}><View style={{flex:1}}><Text style={styles.label}>ORDER</Text><Text style={styles.number}>{order.orderNumber}</Text></View><View style={styles.status}><Text style={styles.statusText}>{order.status??"Processing"}</Text></View></View><View style={styles.divider}/><View style={styles.bottom}><View><Text style={styles.date}>{order.createdAt?new Date(order.createdAt).toLocaleDateString("en-NG"):"Date unavailable"}</Text>{typeof order.total==="number"&&<Text style={styles.total}>{money(order.total,order.currency??"₦")}</Text>}</View><View style={styles.arrow}><Ionicons name="arrow-forward" size={16} color={theme.colors.graphite950}/></View></View></GlassCard></Pressable>)}</ScrollView>}
const styles=StyleSheet.create({screen:{flex:1,backgroundColor:theme.colors.cloud50},content:{padding:18,paddingTop:58,paddingBottom:100},eyebrow:{fontSize:10,fontWeight:"800",letterSpacing:1.4,color:theme.colors.ember600},title:{fontSize:26,fontWeight:"800",letterSpacing:-.7,color:theme.colors.text,marginTop:4},subtitle:{fontSize:13,color:theme.colors.textMuted,marginTop:5,marginBottom:20},press:{marginBottom:10},pressed:{opacity:.86},card:{padding:15,borderRadius:theme.radius.card},row:{flexDirection:"row",alignItems:"center"},label:{fontSize:9,fontWeight:"800",letterSpacing:1.2,color:theme.colors.graphite400},number:{fontSize:15,fontWeight:"700",color:theme.colors.text,marginTop:3},status:{paddingHorizontal:9,paddingVertical:5,borderRadius:4,backgroundColor:theme.colors.cloud100},statusText:{fontSize:10,fontWeight:"700",color:theme.colors.graphite700},divider:{height:1,backgroundColor:theme.colors.graphite200,marginVertical:14},bottom:{flexDirection:"row",alignItems:"center",justifyContent:"space-between"},date:{fontSize:11,color:theme.colors.textMuted},total:{fontSize:16,fontWeight:"700",color:theme.colors.text,marginTop:4},arrow:{width:34,height:34,borderRadius:8,borderWidth:1,borderColor:theme.colors.glassBorder,alignItems:"center",justifyContent:"center"},message:{padding:16,marginBottom:12},error:{color:theme.colors.ember700,fontSize:13},retry:{marginTop:10},retryText:{fontWeight:"700",color:theme.colors.ember600},empty:{padding:24,alignItems:"center"},emptyIcon:{width:44,height:44,borderRadius:10,backgroundColor:theme.colors.cloud100,alignItems:"center",justifyContent:"center"},emptyTitle:{fontSize:17,fontWeight:"800",color:theme.colors.text,marginTop:12},emptyCopy:{fontSize:12.5,color:theme.colors.textMuted,textAlign:"center",marginTop:5,lineHeight:18,maxWidth:280},center:{flex:1,alignItems:"center",justifyContent:"center",backgroundColor:theme.colors.cloud50}});