import { useState } from "react";
import { Alert, KeyboardAvoidingView, Platform, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { Link, useRouter } from "expo-router";
import { GlassCard } from "@/components/GlassCard";
import { api, ApiError } from "@/lib/api";

export default function ForgotPasswordScreen() {
  const router = useRouter(); const [email,setEmail]=useState(""); const [busy,setBusy]=useState(false);
  async function submit(){if(!email.trim())return Alert.alert("Enter your email","We need your TTFL account email to send a reset link.");setBusy(true);try{await api("/api/auth/forgot-password",{method:"POST",body:JSON.stringify({email:email.trim().toLowerCase()})});Alert.alert("Check your email","If an account exists for that address, TTFL has sent password reset instructions.",[{text:"Back to sign in",onPress:()=>router.replace("/(auth)/login")}]);}catch(e){Alert.alert("Could not send reset email",e instanceof ApiError?e.message:"Please try again.")}finally{setBusy(false)}}
  return <KeyboardAvoidingView style={styles.screen} behavior={Platform.OS==="ios"?"padding":undefined}><View style={styles.container}><GlassCard style={styles.card} intensity={28}><Pressable onPress={()=>router.back()}><Text style={styles.back}>‹ Back</Text></Pressable><Text style={styles.title}>Reset your password</Text><Text style={styles.subtitle}>Enter the email connected to your TTFL account and we'll send reset instructions.</Text><TextInput style={styles.input} value={email} onChangeText={setEmail} placeholder="Email" placeholderTextColor="#9ca3af" autoCapitalize="none" keyboardType="email-address"/><Pressable disabled={busy} onPress={submit} style={[styles.button,busy&&styles.disabled]}><Text style={styles.buttonText}>{busy?"Sending…":"Send reset link"}</Text></Pressable><Text style={styles.footer}>Remembered it? <Link href="/(auth)/login" style={styles.link}>Sign in</Link></Text></GlassCard></View></KeyboardAvoidingView>;
}
const styles=StyleSheet.create({screen:{flex:1,backgroundColor:"#f6f6f7"},container:{flex:1,justifyContent:"center",padding:20},card:{borderRadius:26,padding:24},back:{fontSize:14,fontWeight:"700",color:"#666",marginBottom:24},title:{fontSize:30,fontWeight:"800",color:"#111",letterSpacing:-.8},subtitle:{fontSize:15,color:"#6b7280",lineHeight:22,marginTop:8,marginBottom:24},input:{height:54,borderWidth:1,borderColor:"rgba(229,231,235,.95)",borderRadius:14,paddingHorizontal:16,fontSize:16,marginBottom:12,color:"#111",backgroundColor:"rgba(255,255,255,.72)"},button:{height:54,borderRadius:14,backgroundColor:"#111",alignItems:"center",justifyContent:"center",marginTop:4},buttonText:{color:"#fff",fontSize:16,fontWeight:"700"},disabled:{opacity:.55},footer:{textAlign:"center",marginTop:24,color:"#6b7280"},link:{color:"#111",fontWeight:"700"}})
