import { Link, router } from "expo-router";
import { useState } from "react";
import { ActivityIndicator, KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { ApiError } from "@/lib/api";
import { useAuth } from "@/lib/auth";
import { theme } from "@/lib/theme";

const fields=[["firstName","First name"],["lastName","Last name"],["email","Email"],["phone","Phone number"],["password","Password"]] as const;
type FormKey=typeof fields[number][0]; type FormState=Record<FormKey,string>;
function validate(f:FormState){if(Object.values(f).some(v=>!v.trim()))return "Complete all fields.";if(!/^\S+@\S+\.\S+$/.test(f.email.trim()))return "Enter a valid email address.";if(f.phone.trim().length<7)return "A valid phone number is required.";if(f.password.length<8)return "Password must be at least 8 characters.";if(!/[a-z]/.test(f.password)||!/[A-Z]/.test(f.password)||!/[0-9]/.test(f.password))return "Password needs upper, lower, and a number.";return null}
export default function RegisterScreen(){const{signUp}=useAuth();const[form,setForm]=useState<FormState>({firstName:"",lastName:"",email:"",phone:"",password:""});const[error,setError]=useState("");const[busy,setBusy]=useState(false);
async function submit(){setError("");const e=validate(form);if(e)return setError(e);setBusy(true);try{await signUp({...form,firstName:form.firstName.trim(),lastName:form.lastName.trim(),email:form.email.trim().toLowerCase(),phone:form.phone.trim()});router.replace("/(tabs)/home")}catch(err){setError(err instanceof ApiError?err.message:"Unable to create your account right now.")}finally{setBusy(false)}}
return <KeyboardAvoidingView style={styles.screen} behavior={Platform.OS==="ios"?"padding":undefined}><ScrollView contentContainerStyle={styles.shell} keyboardShouldPersistTaps="handled"><View style={styles.form}><Text style={styles.title}>Create your account</Text><Text style={styles.subtitle}>Join TTFL Store and start shopping.</Text><View style={styles.divider}><View style={styles.line}/><Text style={styles.or}>create with email</Text><View style={styles.line}/></View><View style={styles.grid}>{fields.slice(0,2).map(([key,label])=><Field key={key} label={label} value={form[key]} onChangeText={v=>setForm({...form,[key]:v})}/>)}</View>{fields.slice(2).map(([key,label])=><Field key={key} label={label} value={form[key]} onChangeText={v=>setForm({...form,[key]:v})} secureTextEntry={key==="password"} keyboardType={key==="email"?"email-address":key==="phone"?"phone-pad":"default"} autoCapitalize={key==="email"||key==="password"?"none":"words"} hint={key==="password"?"At least 8 characters, with upper, lower, and a number.":undefined}/>)}{!!error&&<Text style={styles.error}>{error}</Text>}<Pressable onPress={submit} disabled={busy} style={({pressed})=>[styles.button,pressed&&styles.pressed,busy&&styles.disabled]}>{busy?<ActivityIndicator color="#fff"/>:<Text style={styles.buttonText}>Create account</Text>}</Pressable><Text style={styles.footer}>Already have an account? <Link href="/(auth)/login" style={styles.link}>Log in</Link></Text></View></ScrollView></KeyboardAvoidingView>}
function Field({label,hint,...props}:{label:string;hint?:string}&React.ComponentProps<typeof TextInput>){return <View style={styles.field}><Text style={styles.label}>{label}</Text><TextInput {...props} style={styles.input}/>{hint&&<Text style={styles.hint}>{hint}</Text>}</View>}
const styles=StyleSheet.create({screen:{flex:1,backgroundColor:theme.colors.cloud50},shell:{flexGrow:1,justifyContent:"center",padding:18,paddingVertical:50},form:{width:"100%",maxWidth:420,alignSelf:"center"},title:{fontSize:21,fontWeight:"800",color:theme.colors.graphite900},subtitle:{fontSize:13,color:theme.colors.graphite600,marginTop:5},divider:{flexDirection:"row",alignItems:"center",gap:10,marginVertical:22},line:{flex:1,height:1,backgroundColor:theme.colors.graphite200},or:{fontSize:11,color:theme.colors.graphite400},grid:{flexDirection:"row",gap:10},field:{flex:1,marginBottom:14},label:{fontSize:13,fontWeight:"600",color:theme.colors.graphite700,marginBottom:5},input:{height:44,borderWidth:1,borderColor:theme.colors.graphite200,borderRadius:7,paddingHorizontal:12,fontSize:14,color:theme.colors.graphite900,backgroundColor:"#fff"},hint:{fontSize:10.5,color:theme.colors.graphite400,marginTop:5,lineHeight:15},error:{backgroundColor:theme.colors.ember100,color:theme.colors.ember700,borderRadius:7,padding:10,fontSize:12},button:{height:44,borderRadius:10,backgroundColor:theme.colors.ember600,alignItems:"center",justifyContent:"center",marginTop:5},buttonText:{color:"#fff",fontSize:13,fontWeight:"700"},pressed:{opacity:.82},disabled:{opacity:.6},footer:{textAlign:"center",marginTop:20,fontSize:13,color:theme.colors.graphite600},link:{color:theme.colors.ember600,fontWeight:"600"}});
